project:
  type: book
  output-dir: _site

book:
  title: "Intro to GIS Training (for Cultural Heritage)"
  author: "Martin Tomko and Brian Armstrong"
  chapters:
      - index.qmd
      - about.qmd
      - whygis.qmd
      - part: "GIS I - Introduction to QGIS"
        chapters:
          - GISI/Install_QGIS.qmd
execute: 
  freeze: true

date-format: "DD MMMM YYYY"

format:
  html: 
    theme: cosmo
