project:
  type: website

website:
  title: "Intro to GIS (using QGIS)"
  navbar:
    left:
      - index.qmd
      - about.qmd
  
execute: 
  freeze: true

date-format: "DD MMMM YYYY"

format:
  html: default
