project:
  type: book
  output-dir: _site

book:
  title: "Intro to GIS Training (for Cultural Heritage)"
  author: "Martin Tomko and Brian Armstrong and Carolyne Nel"
  chapters:
      - index.qmd
      - about.qmd
      - whygis.qmd
      - part: "GIS I - Introduction to QGIS"
        chapters:
          - GISI/install_QGIS.qmd
          - GISI/open_project.qmd
          - GISI/project_setup.qmd
          - GISI/data_work.qmd
      - part: "GIS II - Basic mapmaking with QGIS"
        chapters:
          - GIS_II/cartography_basics.qmd
          - GIS_II/georeferencing.qmd
          - GIS_II/data_editing.qmd
          - GIS_II/print_layout.qmd
      - resources.qmd
execute: 
  freeze: false

date-format: "DD MMMM YYYY"

format:
  html: 
    theme: cosmo
